[workspace]
resolver = "3"
members  = [
  "ffi-wasm",
  "native-app",
]

[workspace.dependencies]
tokio        = { version = "=1.47.0",  default-features = false }
wasm-bindgen = { version = "=0.2.100", default-features = false }
