[package]
name    = "ffi-wasm"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono       = { workspace = true, features = [ "alloc" ] }
wasm-bindgen = { workspace = true, features = [] }
